name: CI

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd

      - name: Set up Python
        uses: actions/setup-python@42375524a9dd64e36d3a0b35416758980d4e46b7
        with:
          python-version: "3.12"

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: poetry install --no-interaction

      - name: Lint
        run: poetry run pre-commit run --all-files
        continue-on-error: true

      - name: Run tests
        run: poetry run pytest
